// <auto-generated />
namespace LibraryCatalogue.Client.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class loadmoviedata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loadmoviedata));
        
        string IMigrationMetadata.Id
        {
            get { return "201905170429210_load movie data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
